url: https://helinyilmaz.github.io
baseurl: /care-assist.github.io

# Site settings
title: CareAssist
email: your-email@domain.com
description: "CareAssist is an AI-powered platform that helps social workers identify children at risk of foster care placement disruption early, enabling faster intervention and better outcomes for children and families."


# Team names, titles and social links
people:
- name: Courtney Chen
  pic: courtney
  position: Data Analysis, Data Engineering, Model Evaluation
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/courtneyjchen/

- name: Samantha Townsend
  pic: samantha
  position: Subject Matter Expert,  Project Manager, Infrastructure & Data Engineering
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/samantha-townsend-a95b841b2/

- name: Helin Yilmaz
  pic: helin
  position: Data Analysis, ML Engineer, UI Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/helin-yilmaz-/

- name: Priscilla Siow
  pic: priss
  position: Product Manager, ML Engineer, UI Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/priscilla-siow/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
