url: https://care-assist.github.io
baseurl:

# Site settings
title: CareAssist
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Courtney Chen
  pic: courtney
  position: Data Analysis, Data Engineering, Model Evaluation
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/courtneyjchen/

- name: Samantha Townsend
  pic: samantha
  position: Subject Matter Expert,  Project Manager, Infrastructure & Data Engineering
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/samantha-townsend-a95b841b2/

- name: Helin Yilmaz
  pic: helin
  position: Data Analysis, ML Engineer, UI Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/helin-yilmaz-/

- name: Priscilla Siow
  pic: priss
  position: Product Manager, ML Engineer, UI Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/priscilla-siow/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
